
name: CI with git hub actions

on:
  push:
    branches: [ master ]
  # pull_requests:
  #   tags:
  #   - '/release/'

jobs:
  helm-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Helm publish"
      uses: draios/action-helm-tools@v1.0.8
      with:
        action: "package"
      env:
        CHART_DIR: flask-chart
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    
    - name: "Helm publish"
      uses: draios/action-helm-tools@v1.0.8
      with:
        action: "publish"
      env:
        CHART_DIR: flask-chart
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}